In [2]:
import tensorflow as tf

In [3]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [4]:
device_name


NameError: ignored

In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences 

In [6]:
sentences = [
    'I love eggs and chicken',
    'I love marijuana and munchies',
    'I hate tomato'
]

In [7]:
max_vocab_size = 20000
tokenizer = Tokenizer(num_words=max_vocab_size)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

In [8]:
print(sequences)

[[1, 2, 4, 3, 5], [1, 2, 6, 3, 7], [1, 8, 9]]


In [9]:
tokenizer.index_word

{1: 'i',
 2: 'love',
 3: 'and',
 4: 'eggs',
 5: 'chicken',
 6: 'marijuana',
 7: 'munchies',
 8: 'hate',
 9: 'tomato'}

In [10]:
data = pad_sequences(sequences, maxlen=5)
data

array([[1, 2, 4, 3, 5],
       [1, 2, 6, 3, 7],
       [0, 0, 1, 8, 9]], dtype=int32)

In [12]:
data =  pad_sequences(sequences,maxlen=5,padding='post')
data

array([[1, 2, 4, 3, 5],
       [1, 2, 6, 3, 7],
       [1, 8, 9, 0, 0]], dtype=int32)

In [15]:
data = pad_sequences(sequences,maxlen=4,truncating='pre')
data

array([[2, 4, 3, 5],
       [2, 6, 3, 7],
       [0, 1, 8, 9]], dtype=int32)